### ISSUE TITLE
Display problem on windows

### ISSUE THREAD

**Issue by agouge** [irstv/orbisgis#602]
During the training session today, many people had problems with the Simple
Style Editor not displaying all elements in preview dialogs. The same GUI seems
to work fine on Linux and (I think) Mac.

From what I've seen online, it looks like we should be adding JPanels to
JFrames, then calling JFrame#pack(), though I'm not sure about this. As of now,
we're just using JPanels.

**Comment by gpetit** [comment]
I tried on Windows 7.
If the resolution of your screen is small, it can be more less useful. But it works. I can see all options present in the simple style editor (I tried different thematic analysis).

**Comment by ebocher** [comment]
So ready to close it ?

**Comment by gpetit** [comment]
Yes I think
