### ISSUE TITLE
Cannot start multiple instance of OrbisGIS

### ISSUE THREAD

**Issue by nicolas-f** [irstv/orbisgis#729]
Each instance of OrbisGIS should not share the same OSGi cache and not the same workspace. This kind of use case is not currently properly handled. We should create file lock or socket lock technique.

Do we prevent OrbisGIS being executed multiple time or we should create an empty (copy?) .OrbisGIS/4.1 folder elsewhere ?

**Comment by nicolas-f** [comment]
I could create an empty file in .OrbisGIS/5.1 then FileLock it ? Releasing this file when OSGi framework is released..
Is it ok ?
https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileLock.html#pdep

**Comment by ebocher** [comment]
Seems ok for me.
