### ISSUE TITLE
SQL Editor do not cache Query

### ISSUE THREAD

**Issue by nicolas-f** [irstv/orbisgis#753]
SQL Console "RunQuery' job read line by line the editor content. If the user change the content of the editor while executing the query then it is seen on the existing "RunQuery" job..

RunQuery job should cache the content of the editor before starting to execute it.

**Comment by ebocher** [comment]
Fixed ?

**Comment by ebocher** [comment]
@gpetit could you test please ?

**Comment by gpetit** [comment]
Yes, seems perfect.
Now during the execution, the user is not able to modify the content of the console
