### ISSUE TITLE
Improve the SQL Console

### ISSUE THREAD

**Issue by gpetit** [irstv/orbisgis#756]
In the SQL Console, when we drag & drop a function, the description is shown as a comment. Sometimes, it can be huge ... so it's not user friendly.

We have to improve this console.
I propose to do something like this

![og](https://cloud.githubusercontent.com/assets/1871248/5245022/457ec138-7956-11e4-87a5-bff9251a27d0.png)

**Comment by ebocher** [comment]
Fix
